const REQUEST_TO_SERVER_FROM_DATA = 'REQUEST_TO_SERVER_FROM_DATA'
const SUCCESS_TO_SERVER_FROM_DATA = 'SUCCESS_TO_SERVER_FROM_DATA'
const ERROR_TO_SERVER_FROM_DATA = 'ERROR_TO_SERVER_FROM_DATA'

const REQUEST_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME =
  'REQUEST_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME'
const SUCCESS_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME =
  'SUCCESS_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME'
const ERROR_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME =
  'ERROR_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME'

const USER_RECORD_NAME_FOR_SEARCH = 'USER_RECORD_NAME_FOR_SEARCH'

const paginationVariable = ['back', 'next']
const variableRowInTable = ['name', 'gender', 'mass', 'eye_color']
const nameRowInTable = ['Name', 'Gender', 'Mass', 'Eye color']

export {
  REQUEST_TO_SERVER_FROM_DATA,
  USER_RECORD_NAME_FOR_SEARCH,
  SUCCESS_TO_SERVER_FROM_DATA,
  ERROR_TO_SERVER_FROM_DATA,
  REQUEST_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME,
  SUCCESS_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME,
  ERROR_TO_SERVER_FROM_DATA_WITH_SEARCH_NAME,
  paginationVariable,
  variableRowInTable,
  nameRowInTable,
}
